import Link from "next/link";

export const metadata = { title: "Privacy Policy — SabiGet" };

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[var(--color-surface)] px-4 py-10 sm:py-16">
      <div className="sabiget-shell max-w-3xl">
        <div className="rounded-2xl border border-[var(--color-line)] bg-[var(--color-surface-strong)] p-6 shadow-[var(--shadow-card)] sm:p-10">
          <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#ff4500]">
            SabiGet
          </p>
          <h1 className="mt-2 text-xl font-extrabold text-[#111111] sm:text-2xl">
            Privacy Policy
          </h1>
          <p className="mt-2 text-sm text-[#8a8a8a]">
            Last reviewed: pending legal finalisation
          </p>

          <div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
            This policy outlines how SabiGet handles your information. Final
            legal review is pending — if you have questions, please contact us
            before relying on this document.
          </div>

          <div className="mt-8 space-y-8 text-sm leading-relaxed text-[#5f5a57]">
            <section>
              <h2 className="text-base font-bold text-[#111111]">
                1. What we collect
              </h2>
              <p className="mt-2">
                When you use SabiGet we collect information you provide directly
                and information generated by your use of the service. This may
                include:
              </p>
              <ul className="mt-2 list-inside list-disc space-y-1 text-[#5f5a57]">
                <li>
                  Account details such as your name, phone number, and email
                  address when you create an account or place an order as a
                  guest.
                </li>
                <li>
                  Order information including items ordered, delivery address,
                  and payment reference.
                </li>
                <li>
                  Location data when you choose to share your device location for
                  vendor discovery or delivery coordination.
                </li>
                <li>
                  Device and usage information necessary to operate and improve
                  the service.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-base font-bold text-[#111111]">
                2. How we use your information
              </h2>
              <p className="mt-2">
                We use the information we collect to provide, maintain, and
                improve the SabiGet service, including to:
              </p>
              <ul className="mt-2 list-inside list-disc space-y-1 text-[#5f5a57]">
                <li>Process orders and coordinate delivery.</li>
                <li>
                  Communicate with you about orders, account activity, and
                  service updates.
                </li>
                <li>
                  Detect and prevent fraud, abuse, and security incidents.
                </li>
                <li>
                  Comply with legal obligations where applicable.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-base font-bold text-[#111111]">
                3. Sharing your information
              </h2>
              <p className="mt-2">
                SabiGet does not sell your personal data. We share information
                only as needed to provide the service, including with:
              </p>
              <ul className="mt-2 list-inside list-disc space-y-1 text-[#5f5a57]">
                <li>
                  Vendors, to the extent necessary to fulfil your order and
                  coordinate delivery.
                </li>
                <li>
                  Payment processors to complete prepaid transactions.
                </li>
                <li>
                  Service providers who assist with operations such as messaging,
                  hosting, and analytics.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-base font-bold text-[#111111]">
                4. Data retention
              </h2>
              <p className="mt-2">
                We retain your information for as long as your account is active
                or as needed to provide the service. Specific retention periods
                for different categories of data are being finalised and will be
                documented here.
              </p>
            </section>

            <section>
              <h2 className="text-base font-bold text-[#111111]">
                5. Your rights
              </h2>
              <p className="mt-2">
                Depending on your location, you may have rights regarding your
                personal data, including the right to access, correct, or delete
                your information. To exercise these rights, please contact us
                through the SabiGet support channel.
              </p>
            </section>

            <section>
              <h2 className="text-base font-bold text-[#111111]">
                6. Changes to this policy
              </h2>
              <p className="mt-2">
                We may update this policy from time to time. When we make
                material changes, we will notify you through the service or by
                other appropriate means.
              </p>
            </section>

            <section>
              <h2 className="text-base font-bold text-[#111111]">7. Contact</h2>
              <p className="mt-2">
                If you have questions about this policy or how we handle your
                data, please reach out through the SabiGet support channel.
              </p>
            </section>
          </div>

          <div className="mt-10 border-t border-[var(--color-line)] pt-6">
            <Link
              href="/"
              className="inline-flex min-h-[44px] items-center text-sm font-semibold text-[#ff4500] hover:underline"
            >
              Back to SabiGet
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
